import './globals.css'
import {Inter, Markazi_Text} from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
// const markazi = Markazi_Text({subsets: ['latin']})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
